### ISSUE TITLE
Trying to update not existing res.partner.title will failed

### ISSUE THREAD

**Issue by hmartinet** [OCA/OpenUpgrade#1228] opened 2017-12-14 09:20 UTC
I have the following error in the migration 8.0 to 9.0 in migration.log:

```
ParseError: "ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne \xab name \xbb
D\xc9TAIL : La ligne en \xe9chec contient (30, 1, 2017-12-14 08:59:44.8588, 2017-12-14 08:59:44.8588, 1, null, null, Sr.)
" while parsing /[…]/9.0/server/openerp/addons/base/migrations/9.0.1.3/noupdate_changes.xml:997, near
<record id="res_partner_title_sir" model="res.partner.title">
  <field name="shortcut">Sr.</field>
</record>
```

This title was deleted by a user in the source database. And the migration wil try to create it with no name. I think some noupdate data should be updated only if exists. But I don't know the cleanest way to do a commit for that. I try to add forcecreate="False" on any res.parter.title record in this file but the error always happens.

**Comment by hmartinet** [comment] 2017-12-14 10:19
I can execute the following query before migration as a workaround:

```
delete from ir_model_data
where module = 'base' and model = 'res.partner.title' 
    and res_id not in (select id from res_partner_title);
```

The migration will not crash on this record but the deleted record will be recreated. Then I can remove it in the migrated database at the end of the process. But if I have a lot of such cases, the process will be very heavy.

**Comment by pedrobaeza** [comment] 2017-12-14 20:31
We have incorporated in openupgradelib an option for ignoring data if they don't exist, but it's not applied to this module and version. See https://github.com/OCA/openupgradelib/pull/80, and check if it can fit for proposing a change.

**Comment by hmartinet** [comment] 2017-12-14 21:08
Ok. Thanks for this information. I will check that next monday because I'm away for 3 days. But that exactly what I'm trying to know before trying to code a custom and bad designed solution.

**Comment by StefanRijnhart** [comment] 2017-12-15 07:40
I don't understand. The entry should be recreated if it doesn't exist because https://github.com/OCA/OpenUpgrade/blob/9.0/openerp/addons/base/res/res_partner_data.xml#L16 is not marked as forcecreate=False.

**Comment by pedrobaeza** [comment] 2017-12-15 07:42
I think in this case he hasn't updated the old version before performing the OpenUpgrade migration.

**Comment by StefanRijnhart** [comment] 2017-12-15 07:48
Oh, but I mean that the migration of the base module from 8.0 to 9.0 itself should recreate the title before the noupdate xml is loaded by the post-migration script.

**Comment by pedrobaeza** [comment] 2017-12-15 07:49
Yeah, I see... then no clue for now

**Comment by hmartinet** [comment] 2017-12-18 09:11
The entry is noupdate"True" and exists in ir_model_data (but res_id represent a removed and unexisting id in res_partner_title), then the record will not be recreated. I think this is the desired behavior by the customer because he want to remove some titles to avoid users used it (There is company rules for partner title). I can confirm removing a title in version 7.0 will not remove the corresponding ir_model_data line, and then the record will never be recreated.

**Comment by StefanRijnhart** [comment] 2017-12-18 10:52
Thanks for the analysis! The dangling XML ids explain why the record is not recreated. However, this must be considered an inconsistency in your Odoo 7.0 system. According to https://github.com/odoo/odoo/blob/7.0/openerp/osv/orm.py#L4093, Odoo will attempt to remove ir_model_data entries upon the deletion of any record.

**Closed as completed by StefanRijnhart** 2017-12-18 10:52 UTC

**Comment by StefanRijnhart** [comment] 2017-12-18 10:54
BTW I am very surprised that you can actually reproduce that there are left over ir_model_data entries after deleting a res.partner.title. On my 7.0 system, this is not the case.
