### ISSUE TITLE
Error migration 6.1->7.0: project addons

### ISSUE THREAD

**Issue by ssaid** [OCA/OpenUpgrade#347] opened 2015-08-15 00:40 UTC
```
2015-08-15 00:22:28,193 84 ERROR openerp.sql_db: Programming error: column "use_tasks" of relation "project_project" does not exist
```

The migration fails in this line addons/project/migrations/7.0.1.1/post-migration.py#97

```
    openupgrade.set_defaults(
        cr, pool, {'project.project': [('use_tasks', None)]})
```

I have checked the official branch odoo/7.0 and this field use_tasks have a default of True but it is not defined in _columns.
Is it correct to remove that line?

**Comment by pedrobaeza** [comment] 2015-08-15 15:21
I have already faced this problem in one migration, and solve it creating by hand the column:

```
ALTER TABLE project_project ADD COLUMN use_tasks BOOLEAN;
```

But I wonder why it happens. @StefanRijnhart, any clue?

**Comment by hbrunn** [comment] 2015-08-16 04:33
@pedrobaeza this is a case to set `use_orm=True` in `set_defaults`, because `use_tasks` is inherited from `account.analytic.account` - it's a regression introduced by your patch to use sql by default. Or we need to make write smarter and be able to write inherited fields.

**Comment by pedrobaeza** [comment] 2015-08-17 18:26
Thanks for pointing out the problem, @hbrunn. Indeed, the inheritance by field delegation is not treated. Are you going to work on this or may I?

**Comment by hbrunn** [comment] 2015-08-17 19:52
@pedrobaeza I did it the bad way in #349, but will pick up @StefanRijnhart's comment soon (hopefully tomorrow) to handle that probably quite common case

**Comment by pedrobaeza** [comment] 2015-08-17 20:16
Thank you. I will review it as soon as you push it.

**Comment by StefanRijnhart** [comment] 2015-10-05 15:01
The related fix has been merged some time ago, so I am closing this issue.

**Closed as completed by StefanRijnhart** 2015-10-05 15:01 UTC
