### ISSUE TITLE
[9.0] account: deletion of view accounts fails on inverse m2o required fields

### ISSUE THREAD

**Issue by sbidoul** [OCA/OpenUpgrade#1455] opened 2018-07-19 12:22 UTC
The 8 to 9 migration fails in presence of mis_builder, because mis.report.instance has a required m2o on the root account, and the account migration deletes view accounts.

I can easily fix that before starting migration, but I'm wondering if there is a better solution that I'd have overlooked.

I guess I'm looking for something similar to end- scripts that would run before everything else.

**Comment by StefanRijnhart** [comment] 2018-07-19 13:12
I think deactivating the accounts instead of deleting them is fine too, but @pedrobaeza was not sure about that I think.

**Comment by pedrobaeza** [comment] 2018-08-09 16:19
The problem is that there's no active field on account.account model. You just have `deprecated` field, which doesn't hide that view accounts from a lot of places, so that's why is far better to remove them.

**Comment by pedrobaeza** [comment] 2018-12-24 12:23
Any news on this?

**Comment by pedrobaeza** [comment] 2019-02-07 18:10
Closing as no news.

**Closed as completed by pedrobaeza** 2019-02-07 18:10 UTC
