### ISSUE TITLE
[8->9] Random result of migrating

### ISSUE THREAD

**Issue by em230418** [OCA/OpenUpgrade#2046] opened 2019-09-30 07:51 UTC
Hi!

Task is migrating demo database from odoo 8 to odoo 9. Result can be randomly successfull (at least finish without error) or failed. Mostly failed result happens.

See 1111.log for failed result and 2222.log for successfull result. Ignore lines like
```
('-----------', 'mail_compose_message', 'type', 'message_type')
```
These are my debug prints.
```diff
diff --git a/openerp/models.py b/openerp/models.py
index d8e69ea27..8257f6928 100644
--- a/openerp/models.py
+++ b/openerp/models.py
@@ -2534,6 +2534,7 @@ class BaseModel(object):
                     if not res and hasattr(f, 'oldname'):
                         res = column_data.get(f.oldname)
                         if res:
+                            print("-----------", self._table, f.oldname, k)
                             cr.execute('ALTER TABLE "%s" RENAME "%s" TO "%s"' % (self._table, f.oldname, k))
                             res['attname'] = k
                             column_data[k] = res
```

[1111.log.gz](https://github.com/OCA/OpenUpgrade/files/3669361/1111.log.gz)
[2222.log.gz](https://github.com/OCA/OpenUpgrade/files/3669363/2222.log.gz)

Dumped database for odoo 8:
[db.sql.gz](https://github.com/OCA/OpenUpgrade/files/3669384/db.sql.gz)

Last commit in my openupgrade copy: b368026c30b7a23bafe197f5c2c6e382a80c4aaf
Last commit in my openupgradelib copy: https://github.com/OCA/openupgradelib/commit/bfc45eca7fb1f19b83e7aa7d10b6bf5e14043136

upd1: my copy openupgradelib includes this patch: https://github.com/OCA/openupgradelib/pull/173.patch based on https://github.com/OCA/openupgradelib/pull/173/files

**Comment by yelizariev** [comment] 2019-09-30 07:57
The error from 1111.log:

```


2019-09-26 12:34:51,525 20516 CRITICAL n1 openerp.service.server: Failed to initialize database `n1`.
Traceback (most recent call last):
  File "/home/noroot/Projects/c8/ou9/openerp/service/server.py", line 894, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/noroot/Projects/c8/ou9/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/noroot/Projects/c8/ou9/openerp/modules/loading.py", line 446, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/noroot/Projects/c8/ou9/openerp/modules/loading.py", line 331, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/home/noroot/Projects/c8/ou9/openerp/modules/loading.py", line 151, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/noroot/Projects/c8/ou9/openerp/modules/migration.py", line 170, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/home/noroot/Projects/c8/ou9/ou9_venv/local/lib/python2.7/site-packages/openupgradelib/openupgrade.py", line 1645, in wrapped_function
    if use_env2 else cr, version)
  File "/home/noroot/Projects/c8/ou9/addons/account/migrations/9.0.1.1/pre-migration.py", line 405, in migrate
    openupgrade.rename_fields(env, field_renames)
  File "/home/noroot/Projects/c8/ou9/ou9_venv/local/lib/python2.7/site-packages/openupgradelib/openupgrade.py", line 555, in rename_fields
    rename_columns(cr, {table: [(old_field, new_field)]})
  File "/home/noroot/Projects/c8/ou9/ou9_venv/local/lib/python2.7/site-packages/openupgradelib/openupgrade.py", line 515, in rename_columns
    'ALTER TABLE "%s" RENAME "%s" TO "%s"' % (table, old, new,))
  File "/home/noroot/Projects/c8/ou9/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/home/noroot/Projects/c8/ou9/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
UndefinedColumn: column "last_reconciliation_date" does not exist

```

**Comment by em230418** [comment] 2019-09-30 08:05
> UndefinedColumn: column "last_reconciliation_date" does not exist

Forgot to mention, that after failed migrating there was field last_time_entries_checked and looks like it new name of last_reconciliation_date

```
2019-09-26 12:34:51,514 20516 INFO n1 openerp.sql_db: Programming error: column "last_reconciliation_date" does not exist
, in query ALTER TABLE "res_partner" RENAME "last_reconciliation_date" TO "last_time_entries_checked"
```

**Comment by em230418** [comment] 2019-09-30 08:06
At least these modules were installed in odoo 8:
```
"bus",
"im_chat",
"base_action_rule",
"project_timesheet",
```

**Comment by pedrobaeza** [comment] 2019-10-11 18:32
This line prevents your error:

https://github.com/OCA/openupgradelib/blob/5a0a2369e08a141a9a5bc8f091c4fc0522b07fa3/openupgradelib/openupgrade.py#L551

so not possible to get to that error without a manipulation.

Closing meanwhile we don't have clear steps to reproduce the problem.

**Closed as completed by pedrobaeza** 2019-10-11 18:32 UTC

**Comment by em230418** [comment] 2019-10-14 06:21
> This line prevents your error:

It didn't. See in 1111.log:

```
2019-09-26 12:34:51,513 20516 DEBUG n1 openerp.sql_db: query: SELECT count(attname) FROM pg_attribute WHERE attrelid = ( SELECT oid FROM pg_class WHERE relname = 'res_partner' ) AND attname = 'last_reconciliation_date'
```

This query came from:
https://github.com/OCA/openupgradelib/blob/5a0a2369e08a141a9a5bc8f091c4fc0522b07fa3/openupgradelib/openupgrade_tools.py#L36-L44

> so not possible to get to that error without a manipulation.

The only manipulation to openupgradelib was this patch: https://github.com/OCA/openupgradelib/pull/173.patch which does not involve this bug. After this patch you will see executing `rename_columns` in line 555 (as in traceback) and `column_exists` check on line before - 554.

**Comment by em230418** [comment] 2019-10-14 06:24
Forgot to mention, running on postgresql 9.5.19

**Comment by pedrobaeza** [comment] 2019-10-14 07:28
That log what represents is the query for the existence of the columns, so nothing strange there. Sorry, but as said, nothing seems to be of OpenUpgrade itself.

**Comment by em230418** [comment] 2019-10-14 11:15
> That log what represents is the query for the existence of the columns, so nothing strange there.

Yes, it does. This is what your mentioned https://github.com/OCA/openupgradelib/blob/5a0a2369e08a141a9a5bc8f091c4fc0522b07fa3/openupgradelib/openupgrade.py#L551 does. But right after that it tries to rename column https://github.com/OCA/openupgradelib/blob/5a0a2369e08a141a9a5bc8f091c4fc0522b07fa3/openupgradelib/openupgrade.py#L552. Here it randomly fails.

**Comment by pedrobaeza** [comment] 2019-10-14 11:18
The only option is that the column exists, and thus the following error doesn't make sense, or your DB system tables are incorrect, so no possible problem at OpenUpgrade level.

**Comment by yelizariev** [comment] 2020-11-16 08:53
From what I know, the problem is not reproduced after switching to postgres 10

**Comment by em230418** [comment] 2020-11-16 09:44
> From what I know, the problem is not reproduced after switching to postgres 10

Agree
