### ISSUE TITLE
[14.0] openupgrade_framework: New installed modules dependencies are not auto-resolved

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/OpenUpgrade#3061] opened 2022-01-09 12:05 UTC
1. Have a 13.0 DB with `account_facturx` installed.
2. Migrate it to 14.0
3. The rename to `account_edi_facturx` is done, but the new dependency `account_edi` is not installed, and thus, the module remains not usable.

**Expected behavior**
Previous framework cycled the needed times over pending to install/to upgrade modules until no one is left or no possible candidate is found, and new dependencies that are not installed, were marked to be installed on the next cycle. This seems to not be replicated on the new framework.

**Current workaround**
Install manually `account_edi` after the migration is done.

**Comment by legalsylvain** [comment] 2022-01-14 08:49
Hi @pedrobaeza thanks for reporting !

> previous framework cycled the needed times over pending to install/to upgrade modules 

Are you talking about odoo or openupgrade framework ?
I don't remember to have removed such code when we isolated patches during the openupgrade refactor with @StefanRijnhart.
Maybe something changed in the core. In a non openupgrade framework, if a new dependency is done on an installed module, making an update install the missing dependency afaik.

Unfortunately, I have no time to investigate immediately on that topic. 
Stefan any idea ?

Regards.

**Comment by pedrobaeza** [comment] 2022-01-14 08:51
It was something specific of OpenUpgrade, touching on `loading.py` if I don't remember bad.

**Comment by MiquelRForgeFlow** [comment] 2022-01-14 09:55
One question. After doing the migration, if you do an --update=all with odoo or OCB, should that module get installed, right?

**Comment by pedrobaeza** [comment] 2022-01-14 10:23
Not sure, but that will be too late, as the migration scripts of the affected modules won't be run until them, and then there can be already data loss or lack of the rest of the framework.

**Comment by StefanRijnhart** [comment] 2022-01-25 20:28
I see the linked PR was closed as "undesirable to solve this in a module's migration script" (with which I agree). Is anybody already chasing a framework solution? Otherwise, I'll gladly have a look this week.

**Comment by pedrobaeza** [comment] 2022-01-25 20:30
I think there isn't anybody, but let's wait for any other answer.

**Comment by MiquelRForgeFlow** [comment] 2022-01-26 08:54
Nobody. Feel free @StefanRijnhart

**Comment by StefanRijnhart** [comment] 2022-01-27 20:34
The problem is caused by the fact that `account_edi_facturx` in Odoo 14 has only *one* dependency, and it is uninstalled at the moment of migration (because it is a new dependency `account_edi` between `account` and `account_edi_facturx`), whereas the modules that are actually going to be updated are any installed modules that depend transitively on the `base` module. IMHO this is a bug in Odoo. I'm proposing a fix in https://github.com/odoo/odoo/pull/83543.

Shall we see what the response is there, or shall I proceed with a workaround in the Openupgrade framework?

**Comment by MiquelRForgeFlow** [comment] 2022-01-28 08:56
If that workaround is not an easy/nice one, then my vote is for "let's wait and see".

**Comment by pedrobaeza** [comment] 2022-02-03 21:05
It seems they are not caring about that :(

**Comment by StefanRijnhart** [comment] 2022-02-15 20:08
OK, here's the patch version https://github.com/OCA/OpenUpgrade/pull/3141

**Comment by StefanRijnhart** [comment] 2022-03-02 12:34
Will be fixed after the merge of https://github.com/odoo/odoo/pull/85663

**Closed as completed by StefanRijnhart** 2022-03-02 12:34 UTC
Labels: bug
