### ISSUE TITLE
[12.0] MemoryError in website pre-migration bootstrap_4_migration

### ISSUE THREAD

**Issue by norlinhenrik** [OCA/OpenUpgrade#2010] opened 2019-09-11 19:09 UTC
Impacted versions:
11.0 to 12.0

Steps to reproduce:
migrate my production database

Current behavior:
[https://github.com/OCA/OpenUpgrade/blob/12.0/addons/website/migrations/12.0.1.0/pre-migration.py#L203](https://github.com/OCA/OpenUpgrade/blob/12.0/addons/website/migrations/12.0.1.0/pre-migration.py#L203)
MemoryError in bootstrap_4_migration

Expected behavior:
Successful migration

Video/Screenshot link (optional):
[AWS EC2 t2.large](https://github.com/OCA/OpenUpgrade/files/3602188/AWS.EC2.t2.large.txt)
[AWS EC2 t2.2xlarge](https://github.com/OCA/OpenUpgrade/files/3602193/AWS.EC2.t2.2xlarge.txt)
[AWS EC2 t2.2xlarge ou12-server.log](https://github.com/OCA/OpenUpgrade/files/3602318/ou12-server.log)
Before migration: 66 records in website_page, 2851 records in ir_ui_view
After migration: 66 records in website_page, 3045 records in ir_ui_view
I have multiple companies & websites. The websites share the same theme_default records.

**Comment by norlinhenrik** [comment] 2019-09-11 20:17
Here is a `free -m` log, updating every ca 15 sec.
[AWS EC2 t2.medium free -m](https://github.com/OCA/OpenUpgrade/files/3602496/AWS.EC2.t2.medium.free.-m.txt)
The ou12-server.log became a little longer now with t2.medium than last time with t2.2xlarge. Eventually the same MemoryError.

I've read that 32-bit python only has access to ~4 GB of RAM. But it seems that I have 64-bit:
`python -c "import struct; print(struct.calcsize('P')*8)"` returns `64` [(from this link)](https://stackoverflow.com/questions/1405913/how-do-i-determine-if-my-python-shell-is-executing-in-32bit-or-64bit-mode-on-os).

**Comment by pedrobaeza** [comment] 2019-09-11 21:05
I think the problem is in shm_size in Postgres. Put 512mb for example.

**Comment by norlinhenrik** [comment] 2019-09-18 04:17
I use postgresql 11.5 and shm_size is not in postgresql.conf.

In postgresql.conf i changed:
shared_buffers = 1280MB (before 128MB)
work_mem = 40MB (before 4MB)
maintenance_work_mem = 640MB (before 64MB)

I did not change:
temp_buffers = 8MB
effective_cache_size = 4GB

Traceback (most recent call last):
  File "/openupgrade12/openupgrade12-server/odoo/fields.py", line 1008, in __get__
    value = record.env.cache.get(record, self)
  File "/openupgrade12/openupgrade12-server/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.ui.view(2539,).inherit_id', None)

Which postgresql variable needs more memory?

**Comment by norlinhenrik** [comment] 2019-09-18 04:32
I got this error in the terminal:
(venv-ou12) henrik@henrik-linux:/openupgrade12$ pu12 -u all -d ag11_0917_to12d
Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(odoo.service.cron.cron0, started daemon 140159876200192)>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 865, in run
Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(odoo.service.cron.cron1, initial daemon)>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
MemoryError
  File "/openupgrade12/openupgrade12-server/odoo/service/server.py", line 400, in target
libgcc_s.so.1 must be installed for pthread_cancel to work

**Comment by pedrobaeza** [comment] 2019-09-18 07:34
Well, shm-size is something of Postgres Docker image (https://hub.docker.com/_/postgres), but as said, it's any parameter of that kind (maybe Python). Any way, this is outside of this issue tracker, as it's not a direct OpenUpgrade problem, so I close this.

**Closed as completed by pedrobaeza** 2019-09-18 07:34 UTC
