### ISSUE TITLE
[11.0] Could not get content for /website_portal_sale/static/src/less/website_portal_sale.less defined in bundle 'web.assets_frontend'.

### ISSUE THREAD

**Issue by davidtranhp** [OCA/OpenUpgrade#1418] opened 2018-06-29 15:55 UTC
### Impacted versions:
11.0
### Steps to reproduce:
1. Finish migration process
2. Go to the website

### Current behavior:
The foolowing error message appears:
```
Could not get content for /website_portal_sale/static/src/less/website_portal_sale.less defined in bundle 'web.assets_frontend'.
```

Look up ir.ui.view records, I found this strange document:
![selection_020](https://user-images.githubusercontent.com/7938973/42102182-60d32c54-7bef-11e8-8002-3f28cbdda475.png)
After removing it, the problem is gone.

**Comment by pedrobaeza** [comment] 2018-06-30 00:11
That weird XML-ID is because the module was merged with sale_payment one because of some common resources, but this view should be removed in normal conditions. Have you checked if the view was marked as noupdate?

**Comment by davidtranhp** [comment] 2018-06-30 00:30
No, it wasn't.

**Comment by patel1008b** [comment] 2018-07-17 16:19
@pedrobaeza @davidtranhp 

Same issue I am facing while migrating v10 ->v11 db. After the migrations when I try to use that db.

Could not get content for /website_portal_sale/static/src/less/website_portal_sale.less defined in bundle 'web.assets_frontend'.&NewLine;Could not get content for /website_payment/static/src/css/website_payment.css defined in bundle 'web.assets_frontend'.

**Comment by pedrobaeza** [comment] 2019-01-14 19:50
This should be solved. Please comment if not.

**Closed as completed by pedrobaeza** 2019-01-14 19:50 UTC

**Comment by mdemaison** [comment] 2019-04-09 11:54
Hi @pedrobaeza , this problem is not solve for me, i migrate my db yesterday (from 10 to 11) with the last version of openupgrade , and i still getting the problem, remove the view resolve the problem

**Comment by pedrobaeza** [comment] 2019-04-12 18:54
I'm not able to reproduce it anymore, but any way, if you remove the view manually, you achieve the same result, so it's good to go.
