### ISSUE TITLE
[10.0] Sales order line "Delivered" not changed when Delivery order validate

### ISSUE THREAD

**Issue by cewolf2002** [OCA/OpenUpgrade#1291] opened 2018-03-19 03:09 UTC
Impacted versions:
10.0

Steps to reproduce:
I just finished migrating from 9.0 to 10.0.
I tested all function and noticed this issue.

Current behavior:
Sales order line "Delivered" not changed when Delivery order validate

Expected behavior:
Delivered Quantity changed when product delivered

Video/Screenshot link (optional):
My migration log: 
https://pastebin.com/izKwXzh9

![2018-03-19 11 01 24](https://user-images.githubusercontent.com/16146906/37576170-00c85fca-2b66-11e8-92fb-19ce024d6b6b.png)
![2018-03-19 11 01 35](https://user-images.githubusercontent.com/16146906/37576171-00f54634-2b66-11e8-94ae-d5418805e5a4.png)

**Comment by pedrobaeza** [comment] 2018-03-19 08:34
Is this a new sales orders? An old one? Is the sales order line linked to the procurement order and the procurement order linked to the move?

**Comment by StefanRijnhart** [comment] 2018-03-21 21:36
I cannot reproduce this. I created a 9.0 database with sale_stock and demo data. I create and confirm a sale order of 2 blank CDs, a product that is invoiced upon delivery. I migrate the database. When I confirm the picking in the migrated database, the delivered quantity jumps from 0 to 2.

**Comment by pedrobaeza** [comment] 2018-03-21 22:43
Me neither with several databases I have migrated, so closing this.

**Closed as completed by pedrobaeza** 2018-03-21 22:43 UTC

**Comment by StefanRijnhart** [comment] 2018-03-22 08:05
@cewolf2002 Please reopen if you have more information about what causes this!
