### ISSUE TITLE
[9.0] technical menus are not fully accessible after migration

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/OpenUpgrade#558] opened 2016-07-20 21:37 UTC
When migrating from openupgrade 9.0 (up to commit 397eebe98ff0e545d39ee74cc7d2922240f53882), and using a demo database withjust module Base installed, the migration finishes with the following messages:
2016-07-20 21:04:25,997 12662 INFO odoo8_migrated openerp.models: Computing parent left and right for table ir_ui_menu...
2016-07-20 21:04:26,090 12662 INFO odoo8_migrated openerp.service.server: Initiating shutdown
2016-07-20 21:04:26,090 12662 INFO odoo8_migrated openerp.service.server: Hit CTRL-C again or send a second signal to force the shutdown.

When you access to table ir_ui_menu on the migrated DB, immediately after the migration, columns 'parent_left' and 'parent_right' are missing from the DB.

If you run an --update=all on an v9 server on the migrated DB it produces no effects. parent_left and parent_right are still not created in the DB.

**Comment by JordiBForgeFlow** [comment] 2016-07-20 23:28
Ok, it's 1:20 AM and I found what was the issue...

In Odoo 9 it is assumed that only the users that belong to group "Extra Rights / Technical Features" will ever have access to the tech features. Still, the user has to activate the debugger mode in addition to belonging to this group.
In a brand new odoo 9 db install the admin user is granted access to this group. (https://github.com/odoo/odoo/blob/9.0/openerp/addons/base/security/base_security.xml#L46)

In Odoo 8, however, this group is optional and not assigned to anyone (https://github.com/odoo/odoo/blob/8.0/openerp/addons/base/security/base_security.xml#L32).

As a consequence, when migrated a DB from 8 to 9 where the admin user does not belong to this group will produce that the admin user is totally unable to access to the technical features (he does not even have access to access to the groups menu to assign himself to this group).

**Comment by JordiBForgeFlow** [comment] 2016-07-20 23:29
My proposal is that openupgrade makes sure that the SUPERUSER will be assigned to base.group_no_one always. cc @hbrunn @StefanRijnhart

**Comment by StefanRijnhart** [comment] 2016-07-21 04:32
The XML stanza that you refer to is non-noupdate, so it should have been be processed. Can you confirm that the features are still accessible in debug mode? In that case, this is not a bug, but an Odoo 9.0 feature. See https://github.com/odoo/odoo/blob/9.0/openerp/models.py#L1379

It is why I wrote https://github.com/OCA/server-tools/tree/9.0/base_technical_features.

Let's start with a test https://github.com/OCA/OpenUpgrade/pull/559

**Comment by hbrunn** [comment] 2016-07-21 04:35
the solution is simple: In OpenUpgrade, this still is noupdate https://github.com/OCA/OpenUpgrade/blob/9.0/openerp/addons/base/security/base_security.xml#L3 - we need another upstream sync

**Comment by StefanRijnhart** [comment] 2016-07-21 04:39
Found that out too https://github.com/odoo/odoo/commit/520243b3cb2f43870bfbc7cd204af44434d419a2

**Comment by StefanRijnhart** [comment] 2016-07-21 04:39
Let me push this

**Comment by hbrunn** [comment] 2016-07-21 05:03
should be fixed with https://github.com/OCA/OpenUpgrade/pull/560
oops @StefanRijnhart, didn't see your message. Hope we didn't duplicate work?

**Comment by StefanRijnhart** [comment] 2016-07-21 05:42
Yes, quite a bit of work. I'll leave the chart digit glitch to you then!

**Comment by StefanRijnhart** [comment] 2016-07-21 05:49
Let's use the Assignee functionality of this bug tracker next time ;-)

**Closed as completed** 2016-07-26 06:40 UTC
Labels: bug

**Comment by StefanRijnhart** [comment] 2016-07-29 19:10
@jbeficent is this bug actually solved? The related test still fails https://travis-ci.org/OCA/OpenUpgrade/builds/148031969
