### ISSUE TITLE
[12.0] Module loading l10n_de failed: file l10n_de/data/res.country.state.csv could not be processed

### ISSUE THREAD

**Issue by OpiumSmoke** [OCA/OpenUpgrade#2308] opened 2020-04-20 11:53 UTC
Impacted versions: 12.0

Steps to reproduce:
Migrate a default database with l10n_de and l10n_de_skr03 installed.

Current behavior:
The file l10n_de/data/res.country.state.csv can not be processed. The entries it contains already exist in the database.

```
2020-04-20 10:22:57,277 2030 INFO database odoo.modules.registry: module l10n_de: creating or updating database tables 
2020-04-20 10:22:58,024 2030 INFO database odoo.modules.loading: loading l10n_de/data/account_account_tags_data.xml 
2020-04-20 10:22:58,397 2030 INFO database odoo.modules.loading: loading l10n_de/data/res.country.state.csv 
2020-04-20 10:22:58,441 2030 ERROR database odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'BW', 57, 'Baden-Württemberg') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(57, BW) already exists.
 
2020-04-20 10:22:58,443 2030 ERROR database odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'BW', 57, 'Baden-Württemberg') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(57, BW) already exists.
 
2020-04-20 10:22:58,463 2030 ERROR database odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'BY', 57, 'Bayern') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(57, BY) already exists.
 
2020-04-20 10:22:58,468 2030 ERROR database odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'BE', 57, 'Berlin') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(57, BE) already exists.
 
2020-04-20 10:22:58,472 2030 ERROR database odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'BB', 57, 'Brandenburg') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(57, BB) already exists.
 
2020-04-20 10:22:58,475 2030 ERROR database odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'HB', 57, 'Bremen') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(57, HB) already exists.
 
2020-04-20 10:22:58,479 2030 ERROR database odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'HH', 57, 'Hamburg') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(57, HH) already exists.
 
2020-04-20 10:22:58,483 2030 ERROR database odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'HE', 57, 'Hessen') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(57, HE) already exists.
 
2020-04-20 10:22:58,490 2030 ERROR database odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'MV', 57, 'Mecklenburg-Vorpommern') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(57, MV) already exists.
 
2020-04-20 10:22:58,493 2030 ERROR database odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'NI', 57, 'Niedersachsen') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(57, NI) already exists.
 
2020-04-20 10:22:58,496 2030 ERROR database odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'NW', 57, 'Nordrhein-Westfalen') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(57, NW) already exists.
 
2020-04-20 10:22:58,501 2030 ERROR database odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'RP', 57, 'Rheinland-Pfalz') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(57, RP) already exists.
 
2020-04-20 10:22:58,505 2030 ERROR database odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'SL', 57, 'Saarland') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(57, SL) already exists.
 
2020-04-20 10:22:58,508 2030 ERROR database odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'SN', 57, 'Sachsen') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(57, SN) already exists.
 
2020-04-20 10:22:58,513 2030 ERROR database odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'ST', 57, 'Sachsen-Anhalt') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(57, ST) already exists.
 
2020-04-20 10:22:58,517 2030 ERROR database odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'SH', 57, 'Schleswig-Holstein') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(57, SH) already exists.
 
2020-04-20 10:22:58,521 2030 ERROR database odoo.sql_db: bad query: INSERT INTO "res_country_state" ("id", "create_uid", "create_date", "write_uid", "write_date", "code", "country_id", "name") VALUES (nextval('res_country_state_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'TH', 57, 'Thüringen') RETURNING id
ERROR: duplicate key value violates unique constraint "res_country_state_name_code_uniq"
DETAIL:  Key (country_id, code)=(57, TH) already exists.
 
2020-04-20 10:22:58,885 2030 WARNING database odoo.modules.loading: Transient module states were reset 
2020-04-20 10:22:58,889 2030 ERROR database odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/username/Documents/projects/odoo/migration/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/username/Documents/projects/odoo/migration/OpenUpgrade/odoo/modules/loading.py", line 480, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/username/Documents/projects/odoo/migration/OpenUpgrade/odoo/modules/loading.py", line 364, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/username/Documents/projects/odoo/migration/OpenUpgrade/odoo/modules/loading.py", line 249, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/username/Documents/projects/odoo/migration/OpenUpgrade/odoo/modules/loading.py", line 72, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/username/Documents/projects/odoo/migration/OpenUpgrade/odoo/tools/convert.py", line 803, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/home/username/Documents/projects/odoo/migration/OpenUpgrade/odoo/tools/convert.py", line 850, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading l10n_de failed: file l10n_de/data/res.country.state.csv could not be processed:
 The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
2020-04-20 10:22:58,891 2030 CRITICAL database odoo.service.server: Failed to initialize database `database`. 
Traceback (most recent call last):
  File "/home/username/Documents/projects/odoo/migration/OpenUpgrade/odoo/service/server.py", line 1151, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/username/Documents/projects/odoo/migration/OpenUpgrade/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/username/Documents/projects/odoo/migration/OpenUpgrade/odoo/modules/loading.py", line 480, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/username/Documents/projects/odoo/migration/OpenUpgrade/odoo/modules/loading.py", line 364, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/username/Documents/projects/odoo/migration/OpenUpgrade/odoo/modules/loading.py", line 249, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/username/Documents/projects/odoo/migration/OpenUpgrade/odoo/modules/loading.py", line 72, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/username/Documents/projects/odoo/migration/OpenUpgrade/odoo/tools/convert.py", line 803, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/home/username/Documents/projects/odoo/migration/OpenUpgrade/odoo/tools/convert.py", line 850, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading l10n_de failed: file l10n_de/data/res.country.state.csv could not be processed:
 The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
The values for the fields 'country_id, code' already exist (they are probably 'Land, Bundesland Kodierung' in the current model).
```

I've tried to exclude the file, but the same issue appears when I import the database into Odoo 12 and run module upgrade.

Any help?

Thanks.

**Comment by KarstenK77** [comment] 2020-08-04 08:58
Same Problem here, after migrating from 11 to 12 I have got same errors when doing -u all. Only workaround, to comment out in `/addons/l10n_de/__manifest__.py:22   # res.country.state.csv`

**Comment by KarstenK77** [comment] 2020-08-05 07:08
In my special case it results cause in past I integrated all german states by myself like this:
```
<data noupdate="1">
        <!-- region German States -->
        <record id="state_de_1" model="res.country.state">
            <field name="name">Baden-Württemberg</field>
            <field name="code">BW</field>
            <field name="country_id" ref="base.de"/>
        </record>
        <record id="state_de_2" model="res.country.state">
            <field name="name">Bayern</field>
            <field name="code">BY</field>
            <field name="country_id" ref="base.de"/>
        </record>
        <record id="state_de_3" model="res.country.state">
            <field name="name">Berlin</field>
            <field name="code">BE</field>
            <field name="country_id" ref="base.de"/>
        </record>
        <record id="state_de_4" model="res.country.state">
            <field name="name">Brandenburg</field>
            <field name="code">BB</field>
            <field name="country_id" ref="base.de"/>
        </record>
        <record id="state_de_5" model="res.country.state">
            <field name="name">Bremen</field>
            <field name="code">HB</field>
            <field name="country_id" ref="base.de"/>
        </record>
        <record id="state_de_6" model="res.country.state">
            <field name="name">Hamburg</field>
            <field name="code">HH</field>
            <field name="country_id" ref="base.de"/>
        </record>
        <record id="state_de_7" model="res.country.state">
            <field name="name">Hessen</field>
            <field name="code">HE</field>
            <field name="country_id" ref="base.de"/>
        </record>
        <record id="state_de_8" model="res.country.state">
            <field name="name">Mecklenburg-Vorpommern</field>
            <field name="code">MV</field>
            <field name="country_id" ref="base.de"/>
        </record>
        <record id="state_de_9" model="res.country.state">
            <field name="name">Niedersachsen</field>
            <field name="code">NI</field>
            <field name="country_id" ref="base.de"/>
        </record>
        <record id="state_de_10" model="res.country.state">
            <field name="name">Nordrhein-Westfalen</field>
            <field name="code">NW</field>
            <field name="country_id" ref="base.de"/>
        </record>
        <record id="state_de_11" model="res.country.state">
            <field name="name">Rheinland-Pfalz</field>
            <field name="code">RP</field>
            <field name="country_id" ref="base.de"/>
        </record>
        <record id="state_de_12" model="res.country.state">
            <field name="name">Saarland</field>
            <field name="code">SL</field>
            <field name="country_id" ref="base.de"/>
        </record>
        <record id="state_de_13" model="res.country.state">
            <field name="name">Sachsen</field>
            <field name="code">SN</field>
            <field name="country_id" ref="base.de"/>
        </record>
        <record id="state_de_14" model="res.country.state">
            <field name="name">Sachsen-Anhalt</field>
            <field name="code">ST</field>
            <field name="country_id" ref="base.de"/>
        </record>
        <record id="state_de_15" model="res.country.state">
            <field name="name">Schleswig-Holstein</field>
            <field name="code">SH</field>
            <field name="country_id" ref="base.de"/>
        </record>
        <record id="state_de_16" model="res.country.state">
            <field name="name">Thüringen</field>
            <field name="code">TH</field>
            <field name="country_id" ref="base.de"/>
        </record>
        <!--        endregion -->
</data>```


Deleting my states from database is no option, cause id reference would get lost. 

In my opinion the problem isn't really rely by OpenUpgrade as by odoo core addon. Iam allready switched to odoo 12.0 and need still that mentioned workaround.

**Comment by pedrobaeza** [comment] 2020-08-05 07:11
Adapt OpenUpgrade to rename the XML-IDs from yours to standard ones.

Closing as no OpenUpgrade bug.

**Closed as completed by pedrobaeza** 2020-08-05 07:11 UTC
