### ISSUE TITLE
8.0 : NameError: name 'openupgrade' is not defined

### ISSUE THREAD

**Issue by judewinne** [OCA/OpenUpgrade#3533] opened 2022-08-17 11:34 UTC
## Module
openupgrade

## Describe the bug
OpenUpgrade/openerp-server
OpenUpgrade/openerp/openupgrade/openupgrade_tools.py", line 1, in <module>
    openupgrade.py
NameError: name 'openupgrade' is not defined

## To Reproduce
1. install openerp 8 and openupgradelib on ubuntu 20
2. launch openerp-server

What should we do to fix that?

**Comment by pedrobaeza** [comment] 2022-08-17 11:38
It seems you are not launching correctly the OpenUpgrade server, but that's out of scope of this issue tracker.

**Closed as completed by pedrobaeza** 2022-08-17 11:38 UTC
Labels: bug

**Comment by judewinne** [comment] 2022-08-17 13:36
Ok but i follow all doc. How should I do that?

**Comment by pedrobaeza** [comment] 2022-08-17 13:50
Publish a talk at Discussions and indicate all you have done with all the possible detail, and with that, people may start to figure out what the problem is.
