### ISSUE TITLE
[9.0] migration death at product_view.xml

### ISSUE THREAD

**Issue by coleste** [OCA/OpenUpgrade#433] opened 2016-02-08 21:55 UTC
Migration process freezes after logging "loading product/product_view.xml". Process stops on its track, no exception or exit.

Problem occurs when validating the record `product_attribute_value_view_tree`. `BaseModel.fields_get()` iterates for `price_extra` but `field.get_description()` never returns. Debugger communication also stops when accessing `_description_digits` prior to this. My guess is Float.digits() never returns.

Problem is created when processing `product_security.xml`. A call to `res_group.write()` flushes the cache through `call_cache_clearing_methods()`. At this point `_description_digits` becomes inaccessible.

Is there a way to keep the cache or restore it?

**Comment by StefanRijnhart** [comment] 2016-02-23 21:03
Interesting. If I remember correctly, Float.digits() requests a cursor before accessing a cached value. This was recently changed to a lazy cursor factory for performance reasons. You could try merging in Odoo to see if that changes anything. What branch are you using? Can I reproduce this behaviour?

**Comment by coleste** [comment] 2016-02-24 21:27
@StefanRijnhart It seems it's a macosx issue. I tried today on an ubuntu 14.04 docker and it goes through product without any glitch.

**Comment by StefanRijnhart** [comment] 2016-02-25 06:05
Wow. Good find!

**Comment by esousy** [comment] 2016-03-13 18:27
I have the same problem in Mac, Win and Linux.
The process freeze in res = self._obj.execute(query, params) in the class sql_db.py.
a new cursor is create  while borrow is locking.
the problem is caused by 'decimal.precision' in product.py, it is registered twice.
when I removed this class from product.py the process pass.
there is any workaround?

**Comment by StefanRijnhart** [comment] 2016-03-14 08:26
Again, try to merge upstream Odoo and see if the lazy cursor factory
fixes the problem

**Comment by pedrobaeza** [comment] 2016-03-16 00:23
Closing this as 9.0 migration is not covered yet.

**Comment by coleste** [comment] 2016-03-18 22:24
@StefanRijnhart fyi, merging didn't fix anything. I had to disable d.clear() in the ormcache class. I don't think it's an issue for migrating.

**Comment by esousy** [comment] 2016-03-19 17:47
Yes, merging didn't fix anything.

**Comment by StefanRijnhart** [comment] 2016-04-21 15:47
Was able to reproduce this. Pushed a fix as #473

**Comment by hbrunn** [comment] 2016-06-07 08:55
closing as https://github.com/OCA/OpenUpgrade/pull/473 was merged a while ago

**Closed as completed by hbrunn** 2016-06-07 08:55 UTC
Labels: bug
