### ISSUE TITLE
Image resizing

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/OpenUpgrade#2316] opened 2020-04-23 14:40 UTC
**Impacted versions:**
Not sure. Migrating from 9.0 to 12.0

I'm migrating a database from 9.0 to 12.0.
I'm not exactly sure which version is reponsible for this, but pictures are not shown properly in the image widget.

I guess Odoo expects a squared image in 12.0, while it didn't in 9.0.

In 9.0, here's how it looked:
![image](https://user-images.githubusercontent.com/1914185/80111631-6aa92700-8580-11ea-9c44-c50fd72a43d8.png)

And in 12.0:
![image](https://user-images.githubusercontent.com/1914185/80111527-477e7780-8580-11ea-9ebe-2b4103b8fbe8.png)

This is the picture in the field image_medium:
![image](https://user-images.githubusercontent.com/1914185/80111700-7f85ba80-8580-11ea-82b2-85fdc7a16258.png)

----

To fix it, I've force odoo to recompute image_medium by re-setting the image field:

```py
    partners = env['res.partner'].search([])
    for partner in partners:
        partner.write({'image': partner.image})
```

It finally looks like this:
![image](https://user-images.githubusercontent.com/1914185/80112010-e30fe800-8580-11ea-8827-38ed3c19196e.png)

Now sure where to put this fix, though :sweat_smile:
Maybe some of you hardcore openupgrade devs can point me in the right direction, or have other ideas on how to manage it?

It'd be great to manage it in a general level, maybe. I'm pretty sure `res.partner` is not the only affected model :thinking:

**Comment by pedrobaeza** [comment] 2020-04-23 14:42
I haven't had that problem in real DBs. Are that demo data? Maybe as they are "hardcoded", they doesn't belong to real situations. Any way, you need to first locate in which version it's happening. Sometimes, bad initial data also leads to this (bug in previous versions that were fixed).

**Comment by ivantodorovich** [comment] 2020-04-23 14:44
It's a real db. I've just didn't want to provide screenshots with real partner data so I've ran the script in a demo db.

But I have the issue in the production db :sweat: 

The issue is because pictures are not squared in 9.0. They all have more height than their width (almost 2x)

**Comment by ivantodorovich** [comment] 2020-04-23 14:46
In 12.0, odoo adds white spaces next to the picture to make it square. 
Because apparently the image widget expects a squared picture.

It wasn't like that in 9.0

**Comment by pedrobaeza** [comment] 2020-04-23 14:46
I migrated several 9.0 without this problem as said. I'm afraid you need to dig a bit more to discover the problem or see if someones knows about that. Any way, the problem is only visualization?

**Comment by ivantodorovich** [comment] 2020-04-23 14:47
The problem is only visualization, yes.
The image widget in 12.0 expects a squared picture

**Comment by pedrobaeza** [comment] 2020-04-23 14:50
> The image widget in 12.0 expects a squared picture

Are you sure about that? I have JPG non-squared perfectly seen in v12. Maybe the problem is with PNG?

**Comment by ivantodorovich** [comment] 2020-04-23 14:53
> > The image widget in 12.0 expects a squared picture
> 
> Are you sure about that? I have JPG non-squared perfectly seen in v12. Maybe the problem is with PNG?

In `12.0`, when you load a non-squared picture, odoo prepares image_medium with white paddings at the sides to make it squared.

In `9.0` odoo didn't add the white paddings, that's why in `'12` it's not visualized properly.

After I force odoo to recreate `image_medium` by re-setting the picture, it works. Odoo adds the paddings to `image_medium` to make it squared.

**Comment by pedrobaeza** [comment] 2020-07-20 19:53
Then do you see something to add in regular OpenUpgrade?

**Comment by pedrobaeza** [comment] 2021-12-18 11:14
No answer, so closing.

**Closed as completed by pedrobaeza** 2021-12-18 11:14 UTC
