### ISSUE TITLE
7 -> 8 : analyse with new API give bad result with functional field

### ISSUE THREAD

**Issue by legalsylvain** [OCA/OpenUpgrade#225] opened 2015-02-05 01:30 UTC
Hi,
I just runned Openupgrade Analysis on an OCA modules 'l10n_fr_siret'.

**V7 Code** (account_financial_tools)

```
class Partner(orm.Model):
    _columns = {
        'siret': fields.function(
            _get_siret, type="char", string='SIRET', method=True, size=14,
            store={
                'res.partner': [lambda self, cr, uid, ids, context=None: ids,
                                ['siren', 'nic'], 10]}),
```

**V8 Code** (l10n_france)

```
class Partner(models.Model):
    siret = fields.Char(
        compute='_get_siret', string='SIRET', size=14, store=True)
```

**Result in analysis file**

```
l10n_fr_siret / res.partner          / siret (char)              : not a function anymore
```

For me, there is no change. It is a functional field in V8 too.

Did you faced the same problem ?

Regards.

**Comment by hbrunn** [comment] 2015-02-05 09:40
I think you're right, please file the problem here: #227

**Comment by legalsylvain** [comment] 2015-03-04 23:35
I tried to investigate this problem tonight without success.
I first thought that it was a bug in openupgrade_records module, but I finally don't think so.
The remote_registry (7.0) says that is a functional field but the local one (8.0) says that it is a normal field.
I'm pretty lost in the registry loading in the Odoo Core.
If someone has an idea ...
Regards.

**Comment by hbrunn** [comment] 2015-03-05 05:07
did you look at _columns or at _fields in v8?

**Comment by StefanRijnhart** [comment] 2015-10-05 15:25
This will be fixed in the 9.0 analysis, as the problem is much more apparent there ;-)

**Comment by pedrobaeza** [comment] 2016-03-16 00:28
I think this is solved, isn't it, @StefanRijnhart?

**Comment by StefanRijnhart** [comment] 2016-03-21 09:29
Yes, backported to at least 7.0.

**Closed as completed by StefanRijnhart** 2016-03-21 09:30 UTC
Labels: bug, work in progress
