### ISSUE TITLE
[11.0] Invalid model name 'procurement.order' in action definition

### ISSUE THREAD

**Issue by davidtranhp** [OCA/OpenUpgrade#1415] opened 2018-06-29 14:04 UTC
### Impacted versions:
11.0

### Steps to reproduce:
```
./odoo-bin -d tvtma10 -u all --stop-after-init
```
### Current behavior:
```
2018-06-29 13:59:54,873 31458 INFO tvtma10 odoo.modules.registry: module stock: creating or updating database tables
2018-06-29 13:59:55,360 31458 INFO tvtma10 odoo.addons.auth_crypt.models.res_users: Hashing passwords, may be slow for databases with many users...
2018-06-29 13:59:56,366 31458 INFO tvtma10 odoo.models: Storing computed values of stock.move.reference
2018-06-29 13:59:56,436 31458 INFO tvtma10 odoo.models: Storing computed values of stock.move.line.product_qty
2018-06-29 13:59:56,446 31458 INFO tvtma10 odoo.models: Storing computed values of stock.move.line.state
2018-06-29 13:59:56,453 31458 INFO tvtma10 odoo.models: Storing computed values of stock.move.line.reference
2018-06-29 13:59:56,648 31458 INFO tvtma10 odoo.models: Storing computed values of stock.picking.scheduled_date
2018-06-29 13:59:56,655 31458 INFO tvtma10 odoo.models: Storing computed values of stock.picking.activity_date_deadline
2018-06-29 13:59:57,912 31458 INFO tvtma10 odoo.modules.loading: loading stock/security/stock_security.xml
2018-06-29 14:00:02,101 31458 INFO tvtma10 odoo.modules.loading: loading stock/security/ir.model.access.csv
2018-06-29 14:00:03,243 31458 INFO tvtma10 odoo.modules.loading: loading stock/views/stock_menu_views.xml
2018-06-29 14:00:03,334 31458 INFO tvtma10 odoo.modules.loading: loading stock/data/stock_traceability_report_data.xml
2018-06-29 14:00:03,340 31458 INFO tvtma10 odoo.modules.loading: loading stock/data/procurement_data.xml
2018-06-29 14:00:03,344 31458 INFO tvtma10 odoo.modules.loading: loading stock/report/report_stock_forecast.xml
2018-06-29 14:00:03,396 31458 INFO tvtma10 odoo.modules.loading: loading stock/report/stock_report_views.xml
2018-06-29 14:00:03,429 31458 INFO tvtma10 odoo.modules.loading: loading stock/report/report_package_barcode.xml
2018-06-29 14:00:03,462 31458 INFO tvtma10 odoo.modules.loading: loading stock/report/report_lot_barcode.xml
2018-06-29 14:00:03,479 31458 INFO tvtma10 odoo.modules.loading: loading stock/report/report_location_barcode.xml
2018-06-29 14:00:03,515 31458 INFO tvtma10 odoo.modules.loading: loading stock/report/report_stockpicking_operations.xml
2018-06-29 14:00:03,543 31458 INFO tvtma10 odoo.modules.loading: loading stock/report/report_deliveryslip.xml
2018-06-29 14:00:03,578 31458 INFO tvtma10 odoo.modules.loading: loading stock/report/report_stockinventory.xml
2018-06-29 14:00:03,598 31458 INFO tvtma10 odoo.modules.loading: loading stock/wizard/stock_change_product_qty_views.xml
2018-06-29 14:00:03,623 31458 INFO tvtma10 odoo.modules.loading: loading stock/wizard/stock_picking_return_views.xml
2018-06-29 14:00:03,648 31458 INFO tvtma10 odoo.modules.loading: loading stock/wizard/stock_scheduler_compute_views.xml
2018-06-29 14:00:03,679 31458 WARNING tvtma10 odoo.modules.loading: Transient module states were reset
2018-06-29 14:00:03,680 31458 ERROR tvtma10 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/tuan/git/openupgrade11/odoo/tools/convert.py", line 748, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/tuan/git/openupgrade11/odoo/tools/convert.py", line 658, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/tuan/git/openupgrade11/odoo/addons/base/ir/ir_model.py", line 1498, in _update
    record.write(values)
  File "/home/tuan/git/openupgrade11/odoo/addons/base/ir/ir_actions.py", line 55, in write
    res = super(IrActions, self).write(vals)
  File "/home/tuan/git/openupgrade11/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/home/tuan/git/openupgrade11/odoo/models.py", line 3256, in _write
    self._validate_fields(vals)
  File "/home/tuan/git/openupgrade11/odoo/models.py", line 1036, in _validate_fields
    check(self)
  File "/home/tuan/git/openupgrade11/odoo/addons/base/ir/ir_actions.py", line 131, in _check_model
    raise ValidationError(_('Invalid model name %r in action definition.') % action.src_model)
odoo.exceptions.ValidationError: ("Invalid model name 'procurement.order' in action definition.", None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tuan/git/openupgrade11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/tuan/git/openupgrade11/odoo/modules/loading.py", line 442, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/tuan/git/openupgrade11/odoo/modules/loading.py", line 328, in load_marked_modules
    upg_registry=upg_registry,
  File "/home/tuan/git/openupgrade11/odoo/modules/loading.py", line 198, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/tuan/git/openupgrade11/odoo/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/tuan/git/openupgrade11/odoo/tools/convert.py", line 795, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/tuan/git/openupgrade11/odoo/tools/convert.py", line 856, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/tuan/git/openupgrade11/odoo/tools/convert.py", line 755, in parse
    exc_info[2]
  File "/home/tuan/git/openupgrade11/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/tuan/git/openupgrade11/odoo/tools/convert.py", line 748, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/tuan/git/openupgrade11/odoo/tools/convert.py", line 658, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/tuan/git/openupgrade11/odoo/addons/base/ir/ir_model.py", line 1498, in _update
    record.write(values)
  File "/home/tuan/git/openupgrade11/odoo/addons/base/ir/ir_actions.py", line 55, in write
    res = super(IrActions, self).write(vals)
  File "/home/tuan/git/openupgrade11/odoo/models.py", line 3090, in write
    self._write(old_vals)
  File "/home/tuan/git/openupgrade11/odoo/models.py", line 3256, in _write
    self._validate_fields(vals)
  File "/home/tuan/git/openupgrade11/odoo/models.py", line 1036, in _validate_fields
    check(self)
  File "/home/tuan/git/openupgrade11/odoo/addons/base/ir/ir_actions.py", line 131, in _check_model
    raise ValidationError(_('Invalid model name %r in action definition.') % action.src_model)
odoo.tools.convert.ParseError: "Invalid model name 'procurement.order' in action definition.
None" while parsing /home/tuan/git/openupgrade11/addons/stock/wizard/stock_scheduler_compute_views.xml:20, near
<record id="action_procurement_compute" model="ir.actions.act_window">
        <field name="name">Run Scheduler</field>
        <field name="res_model">stock.scheduler.compute</field>
        <field name="view_type">form</field>
        <field name="view_mode">form</field>
        <field name="target">new</field>
    </record>
2018-06-29 14:00:03,682 31458 CRITICAL tvtma10 odoo.service.server: Failed to initialize database `tvtma10`.
```

**Comment by pedrobaeza** [comment] 2018-06-29 14:21
Duplicate of #1376

**Closed as completed by pedrobaeza** 2018-06-29 14:21 UTC
